In [1]:
# Imports
import numpy as np
import pandas as pd

In [2]:
def print_neighbors_with_distance(matrix, max_distance):
    rows, cols = len(matrix), len(matrix[0])

    for i in range(rows):
        for j in range(cols):
            # Neighbors
            neighbors = []

            # Iterate over all possible neighbors within the max_distance
            for x in range(max(0, i - max_distance), min(i + max_distance + 1, rows)):
                for y in range(max(0, j - max_distance), min(j + max_distance + 1, cols)):
                    if (x, y) != (i, j) and abs(x - i) + abs(y - j) <= max_distance:
                        neighbors.append(matrix[x][y])

            # Print the result for the current element
            for k in neighbors:
                print(matrix[i][j],k)
            

# AMPL Model usage:
matrix = np.arange(1, 65).reshape((8, 8))
max_distance = 2
print_neighbors_with_distance(matrix, max_distance)
print(matrix)

1 2
1 3
1 9
1 10
1 17
2 1
2 3
2 4
2 9
2 10
2 11
2 18
3 1
3 2
3 4
3 5
3 10
3 11
3 12
3 19
4 2
4 3
4 5
4 6
4 11
4 12
4 13
4 20
5 3
5 4
5 6
5 7
5 12
5 13
5 14
5 21
6 4
6 5
6 7
6 8
6 13
6 14
6 15
6 22
7 5
7 6
7 8
7 14
7 15
7 16
7 23
8 6
8 7
8 15
8 16
8 24
9 1
9 2
9 10
9 11
9 17
9 18
9 25
10 1
10 2
10 3
10 9
10 11
10 12
10 17
10 18
10 19
10 26
11 2
11 3
11 4
11 9
11 10
11 12
11 13
11 18
11 19
11 20
11 27
12 3
12 4
12 5
12 10
12 11
12 13
12 14
12 19
12 20
12 21
12 28
13 4
13 5
13 6
13 11
13 12
13 14
13 15
13 20
13 21
13 22
13 29
14 5
14 6
14 7
14 12
14 13
14 15
14 16
14 21
14 22
14 23
14 30
15 6
15 7
15 8
15 13
15 14
15 16
15 22
15 23
15 24
15 31
16 7
16 8
16 14
16 15
16 23
16 24
16 32
17 1
17 9
17 10
17 18
17 19
17 25
17 26
17 33
18 2
18 9
18 10
18 11
18 17
18 19
18 20
18 25
18 26
18 27
18 34
19 3
19 10
19 11
19 12
19 17
19 18
19 20
19 21
19 26
19 27
19 28
19 35
20 4
20 11
20 12
20 13
20 18
20 19
20 21
20 22
20 27
20 28
20 29
20 36
21 5
21 12
21 13
21 14
21 19
21 20
21 22
21 23
21 28
21 29


In [3]:
# Import cleaned-up csv file
df = pd.read_csv("https://raw.githubusercontent.com/makhoullillian153/D2p-fall-2023/main/mission_data.csv")

# Declare and initialize nodes set
nodes = range(1,65)
mat = np.array(range(1,5625))

# Declare intervals of coordinates
a = np.arange(-108, -103.5 ,0.5) # x coordinates - 8 intervals
b = np.arange(38, 41.375, 0.375) # y coordinates - 8 intervals

# Declaring parameter val
val = np.zeros((8,8)) 

# Initializing paramter val
for i in range(8):
  for j in range(8):
    for k in range(df.shape[0]):
      if (a[i] < df.iloc[k, 25] <= a[i + 1]):
        if (b[j] < df.iloc[k, 26] <= b [j+1]):
          val[i][j] += df.iloc[k, 18] # add to respective bucket
          df.drop(k, axis = 0) # to optimize code
        if df.shape[0] == 0:
          break

print(val)

[[ 2.  0.  0.  0.  1.  0.  0.  0.]
 [ 0.  2.  6. 28.  5.  0.  0.  0.]
 [ 3.  5. 28. 53. 50.  1.  0.  0.]
 [ 1. 10. 45. 72. 65.  1.  0.  0.]
 [ 3.  7.  6. 74. 24. 23. 19. 13.]
 [ 6. 50.  7. 24.  3. 95. 39. 14.]
 [ 0.  2.  4.  2.  3.  0.  1.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]]
